import { existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { spawn, type ChildProcessWithoutNullStreams } from "node:child_process";

export interface YouTubeSearchResult {
  id: string;
  title: string;
  url: string;
  channel?: string;
  durationSec?: number;
  thumbnailUrl?: string;
}

export interface YouTubePlaylistResult {
  title?: string;
  items: YouTubeSearchResult[];
}

interface SubtitleTrack {
  lang: string;
  url: string;
  ext?: string;
  autoGenerated: boolean;
}

interface SubtitleCue {
  startSec: number;
  endSec: number;
  text: string;
}

export interface YouTubeVideoMeta {
  id: string;
  title: string;
  url: string;
  channel?: string;
  durationSec?: number;
  thumbnailUrl?: string;
  subtitleTracks: SubtitleTrack[];
}

export interface YouTubeOverlayState {
  playing: boolean;
  ready: boolean;
  ended: boolean;
  title: string;
  channel?: string;
  currentTimeSec: number;
  durationSec?: number;
  statusMessage: string;
  audioAvailable: boolean;
  audioEnabled: boolean;
  audioMuted: boolean;
  audioVolume: number;
  audioStatus: string;
  subtitlesAvailable: boolean;
  subtitlesEnabled: boolean;
  subtitleStatus: string;
  subtitleText?: string;
}

interface YouTubePlaybackSources {
  videoUrl: string;
  audioUrl?: string;
}

interface YouTubeEngineOptions {
  audioEnabled?: boolean;
  muted?: boolean;
  volume?: number;
  subtitlesEnabled?: boolean;
}

interface WindowsAudioProcessCallbacks {
  onReady?: () => void;
  onError?: (message: string) => void;
  onExit?: () => void;
}

const FRAME_WIDTH = 160;
const FRAME_HEIGHT = 90;
const TARGET_FPS = 12;
const FRAME_BYTES = FRAME_WIDTH * FRAME_HEIGHT * 4;
const DEFAULT_VOLUME = 70;

const __dirname = dirname(fileURLToPath(import.meta.url));
const BIN_DIR = join(__dirname, "bin");
const YT_DLP_PATH = join(BIN_DIR, process.platform === "win32" ? "yt-dlp.exe" : "yt-dlp");
const AUDIO_SCRIPT_PATH = join(__dirname, "wmplayer-audio.ps1");

let ytDlpClassPromise: Promise<any> | null = null;
let ffmpegPathPromise: Promise<string> | null = null;
let ytDlpReadyPromise: Promise<void> | null = null;

async function getYTDlpClass(): Promise<any> {
  if (!ytDlpClassPromise) {
    ytDlpClassPromise = import("yt-dlp-wrap").then((mod: any) => mod?.default?.default ?? mod?.default ?? mod);
  }
  return ytDlpClassPromise;
}

async function getFfmpegPath(): Promise<string> {
  if (!ffmpegPathPromise) {
    ffmpegPathPromise = import("ffmpeg-static").then((mod: any) => mod?.default ?? mod);
  }
  return ffmpegPathPromise;
}

async function ensureYtDlpBinary(): Promise<string> {
  if (!ytDlpReadyPromise) {
    ytDlpReadyPromise = (async () => {
      mkdirSync(BIN_DIR, { recursive: true });
      if (!existsSync(YT_DLP_PATH)) {
        const YTDlpWrap = await getYTDlpClass();
        await YTDlpWrap.downloadFromGithub(YT_DLP_PATH, undefined, process.platform);
      }
    })();
  }

  await ytDlpReadyPromise;
  return YT_DLP_PATH;
}

async function createYtDlp(): Promise<any> {
  const YTDlpWrap = await getYTDlpClass();
  const binaryPath = await ensureYtDlpBinary();
  return new YTDlpWrap(binaryPath);
}

function cleanText(value: unknown, fallback = "Unknown"): string {
  if (typeof value !== "string") return fallback;
  const trimmed = value.replace(/\s+/g, " ").trim();
  return trimmed || fallback;
}

function normalizeDuration(value: unknown): number | undefined {
  return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : undefined;
}

function clamp(value: number, min: number, max: number): number {
  return Math.max(min, Math.min(max, value));
}

function trimYtDlpStdout(stdout: string): string {
  return stdout
    .split(/\r?\n/)
    .map((line) => line.trim())
    .filter(Boolean)
    .join("\n");
}

function extractThumbnailUrl(entry: any): string | undefined {
  if (typeof entry?.thumbnail === "string" && entry.thumbnail) return entry.thumbnail;
  const thumbnails = Array.isArray(entry?.thumbnails) ? entry.thumbnails : [];
  const last = thumbnails[thumbnails.length - 1];
  return typeof last?.url === "string" ? last.url : undefined;
}

function normalizeVideoUrl(value: any, fallbackId?: string): string | undefined {
  if (typeof value === "string" && /^https?:\/\//i.test(value)) return value;
  const id = typeof value === "string" && value ? value : fallbackId;
  return id ? `https://www.youtube.com/watch?v=${id}` : undefined;
}

function supportsAudioPlayback(): boolean {
  return process.platform === "win32" && existsSync(AUDIO_SCRIPT_PATH);
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&nbsp;/g, " ");
}

function cleanSubtitleText(text: string): string {
  return decodeEntities(text)
    .replace(/<[^>]+>/g, "")
    .replace(/\[[^\]]+\]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function parseTimecode(value: string): number {
  const normalized = value.trim().replace(",", ".");
  const parts = normalized.split(":").map((part) => Number(part));
  if (parts.some((part) => !Number.isFinite(part))) return 0;
  if (parts.length === 3) {
    return parts[0]! * 3600 + parts[1]! * 60 + parts[2]!;
  }
  if (parts.length === 2) {
    return parts[0]! * 60 + parts[1]!;
  }
  return parts[0] ?? 0;
}

function parseVtt(text: string): SubtitleCue[] {
  const cues: SubtitleCue[] = [];
  const normalized = text.replace(/^WEBVTT.*$/m, "").replace(/\r/g, "");
  const blocks = normalized.split(/\n\n+/);

  for (const block of blocks) {
    const lines = block.split("\n").map((line) => line.trim()).filter(Boolean);
    if (lines.length === 0) continue;

    const timeLineIndex = lines.findIndex((line) => line.includes("-->") && /\d/.test(line));
    if (timeLineIndex === -1) continue;

    const match = lines[timeLineIndex]!.match(/([^\s]+)\s+-->\s+([^\s]+)/);
    if (!match) continue;

    const startSec = parseTimecode(match[1]!);
    const endSec = parseTimecode(match[2]!);
    const textLines = lines.slice(timeLineIndex + 1);
    const cueText = cleanSubtitleText(textLines.join(" "));
    if (!cueText) continue;

    cues.push({ startSec, endSec, text: cueText });
  }

  return cues;
}

function parseJson3(text: string): SubtitleCue[] {
  const data = JSON.parse(text);
  const events = Array.isArray(data?.events) ? data.events : [];
  const cues: SubtitleCue[] = [];

  for (const event of events) {
    const startMs = typeof event?.tStartMs === "number" ? event.tStartMs : undefined;
    const durationMs = typeof event?.dDurationMs === "number" ? event.dDurationMs : undefined;
    const segs = Array.isArray(event?.segs) ? event.segs : [];
    if (startMs === undefined || durationMs === undefined || segs.length === 0) continue;

    const textValue = cleanSubtitleText(
      segs
        .map((seg: any) => (typeof seg?.utf8 === "string" ? seg.utf8 : ""))
        .join(" "),
    );
    if (!textValue) continue;

    cues.push({
      startSec: startMs / 1000,
      endSec: (startMs + durationMs) / 1000,
      text: textValue,
    });
  }

  return cues;
}

function pickTrackVariant(tracks: any[], autoGenerated: boolean, lang: string): SubtitleTrack | null {
  const variants = Array.isArray(tracks) ? tracks : [];
  const preference = ["vtt", "json3", "srv3", "ttml"];

  for (const ext of preference) {
    const hit = variants.find((track: any) => typeof track?.url === "string" && track?.ext === ext);
    if (hit) {
      return { lang, url: hit.url, ext: hit.ext, autoGenerated };
    }
  }

  const fallback = variants.find((track: any) => typeof track?.url === "string");
  if (!fallback) return null;
  return { lang, url: fallback.url, ext: fallback.ext, autoGenerated };
}

function extractSubtitleTracks(info: any): SubtitleTrack[] {
  const collected: SubtitleTrack[] = [];
  const addTracks = (source: any, autoGenerated: boolean) => {
    if (!source || typeof source !== "object") return;
    for (const [lang, variants] of Object.entries(source)) {
      const picked = pickTrackVariant(variants as any[], autoGenerated, lang);
      if (picked) collected.push(picked);
    }
  };

  addTracks(info?.subtitles, false);
  addTracks(info?.automatic_captions, true);
  return collected;
}

function chooseSubtitleTrack(tracks: SubtitleTrack[]): SubtitleTrack | null {
  if (tracks.length === 0) return null;
  const preferredLangs = ["en", "en-us", "en-gb"];

  const rank = (track: SubtitleTrack): number => {
    const lang = track.lang.toLowerCase();
    const langScore = preferredLangs.includes(lang)
      ? 0
      : preferredLangs.some((candidate) => lang.startsWith(candidate))
        ? 1
        : lang.startsWith("en")
          ? 2
          : 3;
    const autoScore = track.autoGenerated ? 1 : 0;
    const extScore = track.ext === "vtt" ? 0 : track.ext === "json3" ? 1 : 2;
    return langScore * 100 + autoScore * 10 + extScore;
  };

  return [...tracks].sort((a, b) => rank(a) - rank(b))[0] ?? null;
}

async function loadSubtitleCues(track: SubtitleTrack): Promise<SubtitleCue[]> {
  const response = await fetch(track.url, {
    headers: {
      "user-agent": "Mozilla/5.0",
    },
  });

  if (!response.ok) {
    throw new Error(`subtitle fetch failed (${response.status})`);
  }

  const contentType = response.headers.get("content-type") ?? "";
  const body = await response.text();
  const ext = (track.ext ?? "").toLowerCase();

  if (ext === "vtt" || /vtt/i.test(contentType) || body.includes("WEBVTT")) {
    return parseVtt(body);
  }

  if (ext === "json3" || /json/i.test(contentType)) {
    return parseJson3(body);
  }

  if (body.trim().startsWith("{")) {
    return parseJson3(body);
  }

  return parseVtt(body);
}

class WindowsAudioProcess {
  private child: ChildProcessWithoutNullStreams | null;
  private stdoutBuffer = "";
  private stderrBuffer = "";

  constructor(
    audioUrl: string,
    startTimeSec: number,
    volume: number,
    muted: boolean,
    private callbacks: WindowsAudioProcessCallbacks = {},
  ) {
    this.child = spawn(
      "powershell",
      [
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        AUDIO_SCRIPT_PATH,
        "-AudioUrl",
        audioUrl,
        "-StartSeconds",
        startTimeSec.toFixed(3),
        "-Volume",
        String(clamp(Math.round(volume), 0, 100)),
        ...(muted ? ["-Muted"] : []),
      ],
      {
        stdio: ["pipe", "pipe", "pipe"],
        windowsHide: true,
      },
    );

    this.child.stdout.on("data", (chunk: Buffer) => {
      this.stdoutBuffer += chunk.toString("utf8");
      this._drainStdout();
    });

    this.child.stderr.on("data", (chunk: Buffer) => {
      this.stderrBuffer = `${this.stderrBuffer}${chunk.toString("utf8")}`.slice(-1000);
    });

    this.child.on("error", (error) => {
      this.callbacks.onError?.(error.message);
    });

    this.child.on("close", () => {
      const stderr = this.stderrBuffer.trim();
      if (stderr) {
        this.callbacks.onError?.(stderr);
      }
      this.child = null;
      this.callbacks.onExit?.();
    });
  }

  private _drainStdout(): void {
    if (!this.stdoutBuffer.includes("\n")) return;

    const lines = this.stdoutBuffer.split(/\r?\n/);
    this.stdoutBuffer = lines.pop() ?? "";

    for (const rawLine of lines) {
      const line = rawLine.trim();
      if (!line) continue;
      if (line === "ready") {
        this.callbacks.onReady?.();
      } else if (line.startsWith("error:")) {
        this.callbacks.onError?.(line.slice("error:".length).trim() || "Unknown audio error");
      }
    }
  }

  setVolume(volume: number): void {
    this._send(`volume ${clamp(Math.round(volume), 0, 100)}`);
  }

  setMuted(muted: boolean): void {
    this._send(`mute ${muted ? "on" : "off"}`);
  }

  dispose(): void {
    const child = this.child;
    this.child = null;
    if (!child) return;

    try {
      child.stdin.write("quit\n");
      child.stdin.end();
    } catch {
      // Ignore teardown races.
    }

    setTimeout(() => {
      try {
        child.kill();
      } catch {
        // Ignore shutdown races.
      }
    }, 200);
  }

  private _send(command: string): void {
    if (!this.child || this.child.killed || this.child.stdin.destroyed) return;
    try {
      this.child.stdin.write(`${command}\n`);
    } catch {
      // Ignore shutdown races.
    }
  }
}

export function looksLikeYouTubeUrl(value: string): boolean {
  return /^(https?:\/\/)?(www\.)?(youtube\.com|youtu\.be)\//i.test(value.trim());
}

export function formatClock(seconds: number | undefined): string {
  if (!seconds || !Number.isFinite(seconds) || seconds < 0) return "0:00";
  const total = Math.floor(seconds);
  const h = Math.floor(total / 3600);
  const m = Math.floor((total % 3600) / 60);
  const s = total % 60;
  if (h > 0) return `${h}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
  return `${m}:${String(s).padStart(2, "0")}`;
}

export async function searchYouTube(query: string, limit = 8): Promise<YouTubeSearchResult[]> {
  const ytDlp = await createYtDlp();
  const stdout = await ytDlp.execPromise([
    `ytsearch${limit}:${query}`,
    "--dump-single-json",
    "--no-warnings",
    "--skip-download",
  ]);

  const data = JSON.parse(trimYtDlpStdout(stdout));
  const entries = Array.isArray(data?.entries) ? data.entries : [];

  return entries
    .map((entry: any) => ({
      id: cleanText(entry?.id, "unknown"),
      title: cleanText(entry?.title),
      url: normalizeVideoUrl(entry?.webpage_url, entry?.id),
      channel: cleanText(entry?.channel ?? entry?.uploader ?? entry?.channel_id ?? "", ""),
      durationSec: normalizeDuration(entry?.duration),
      thumbnailUrl: extractThumbnailUrl(entry),
    }))
    .filter((entry: YouTubeSearchResult) => Boolean(entry.url && entry.id && entry.title));
}

export async function loadYouTubePlaylist(url: string, limit = 20): Promise<YouTubePlaylistResult> {
  const ytDlp = await createYtDlp();
  const stdout = await ytDlp.execPromise([
    url,
    "--flat-playlist",
    "--dump-single-json",
    "--playlist-end",
    String(limit),
    "--no-warnings",
    "--skip-download",
  ]);

  const data = JSON.parse(trimYtDlpStdout(stdout));
  const entries = Array.isArray(data?.entries) ? data.entries : [];
  const items = entries
    .map((entry: any) => ({
      id: cleanText(entry?.id, "unknown"),
      title: cleanText(entry?.title),
      url: normalizeVideoUrl(entry?.webpage_url ?? entry?.url, entry?.id),
      channel: cleanText(entry?.channel ?? entry?.uploader ?? entry?.channel_id ?? "", ""),
      durationSec: normalizeDuration(entry?.duration),
      thumbnailUrl: extractThumbnailUrl(entry),
    }))
    .filter((entry: YouTubeSearchResult) => Boolean(entry.url && entry.id && entry.title));

  return {
    title: cleanText(data?.title ?? data?.playlist_title ?? "", ""),
    items,
  };
}

export class YouTubeOverlayEngine {
  readonly frameWidth = FRAME_WIDTH;
  readonly frameHeight = FRAME_HEIGHT;
  readonly fps = TARGET_FPS;

  private _meta: YouTubeVideoMeta;
  private _frame = new Uint8Array(FRAME_BYTES);
  private _statusMessage = "Idle";
  private _ready = false;
  private _playing = false;
  private _ended = false;
  private _disposed = false;
  private _currentTimeSec = 0;
  private _carry = Buffer.alloc(0);
  private _ffmpeg: ChildProcessWithoutNullStreams | null = null;
  private _serial: Promise<void> = Promise.resolve();
  private _spawnToken = 0;
  private _stderrTail = "";
  private _audioAvailable = supportsAudioPlayback();
  private _audioEnabled = this._audioAvailable;
  private _audioMuted = false;
  private _audioVolume = DEFAULT_VOLUME;
  private _audioStatus = this._audioAvailable ? `Volume ${DEFAULT_VOLUME}%` : "Audio unavailable on this platform";
  private _audioProcess: WindowsAudioProcess | null = null;
  private _currentAudioUrl: string | null = null;
  private _subtitleTracks: SubtitleTrack[];
  private _subtitleCues: SubtitleCue[] = [];
  private _subtitlesEnabled = false;
  private _subtitleStatus = "Subtitles off";
  private _activeSubtitleTrack: SubtitleTrack | null = null;

  constructor(meta: YouTubeVideoMeta, startTimeSec = 0) {
    this._meta = meta;
    this._subtitleTracks = meta.subtitleTracks;
    this._currentTimeSec = Math.max(0, startTimeSec);
    if (this._subtitleTracks.length === 0) {
      this._subtitleStatus = "No subtitles found";
    }
  }

  static async fromUrl(url: string, startTimeSec = 0): Promise<YouTubeOverlayEngine> {
    const meta = await this.fetchMeta(url);
    return new YouTubeOverlayEngine(meta, startTimeSec);
  }

  static async fetchMeta(url: string): Promise<YouTubeVideoMeta> {
    const ytDlp = await createYtDlp();
    const info = await ytDlp.getVideoInfo(url);

    return {
      id: cleanText(info?.id, url),
      title: cleanText(info?.title),
      url: typeof info?.webpage_url === "string" ? info.webpage_url : url,
      channel: cleanText(info?.channel ?? info?.uploader ?? "", ""),
      durationSec: normalizeDuration(info?.duration),
      thumbnailUrl: extractThumbnailUrl(info),
      subtitleTracks: extractSubtitleTracks(info),
    };
  }

  matchesUrl(url: string): boolean {
    const normalized = url.trim();
    return normalized === this._meta.url || normalized.includes(this._meta.id);
  }

  get videoUrl(): string {
    return this._meta.url;
  }

  get videoId(): string {
    return this._meta.id;
  }

  get title(): string {
    return this._meta.title;
  }

  get ready(): boolean {
    return this._ready;
  }

  get statusMessage(): string {
    return this._statusMessage;
  }

  getFrameRGBA(): Uint8Array {
    return this._frame;
  }

  getState(): YouTubeOverlayState {
    return {
      playing: this._playing,
      ready: this._ready,
      ended: this._ended,
      title: this._meta.title,
      channel: this._meta.channel,
      currentTimeSec: this._currentTimeSec,
      durationSec: this._meta.durationSec,
      statusMessage: this._statusMessage,
      audioAvailable: this._audioAvailable,
      audioEnabled: this._audioEnabled,
      audioMuted: this._audioMuted,
      audioVolume: this._audioVolume,
      audioStatus: this._audioStatus,
      subtitlesAvailable: this._subtitleTracks.length > 0,
      subtitlesEnabled: this._subtitlesEnabled,
      subtitleStatus: this._subtitleStatus,
      subtitleText: this._subtitlesEnabled ? this._getSubtitleTextAt(this._currentTimeSec) : undefined,
    };
  }

  configure(options: YouTubeEngineOptions): Promise<void> {
    return this._queue(async () => {
      if (typeof options.audioEnabled === "boolean") {
        this._audioEnabled = options.audioEnabled && this._audioAvailable;
      }
      if (typeof options.muted === "boolean") {
        this._audioMuted = options.muted;
      }
      if (typeof options.volume === "number" && Number.isFinite(options.volume)) {
        this._audioVolume = clamp(Math.round(options.volume), 0, 100);
      }

      if (typeof options.subtitlesEnabled === "boolean") {
        await this._setSubtitlesEnabledInternal(options.subtitlesEnabled);
      }

      if (!this._audioEnabled) {
        this._stopAudioProcess();
      } else if (this._playing && !this._audioProcess && this._currentAudioUrl) {
        this._startAudioProcess(this._currentAudioUrl, this._currentTimeSec);
      }

      this._audioProcess?.setVolume(this._audioVolume);
      this._audioProcess?.setMuted(this._audioMuted);
      this._audioStatus = this._describeAudioState();
    });
  }

  play(): Promise<void> {
    return this._queue(async () => {
      if (this._disposed || this._playing) return;
      await this._startDecoder(this._currentTimeSec);
    });
  }

  pause(): Promise<void> {
    return this._queue(async () => {
      this._stopDecoder("Paused");
    });
  }

  togglePause(): Promise<void> {
    return this._playing ? this.pause() : this.play();
  }

  seekBy(deltaSec: number): Promise<void> {
    return this.seekTo(this._currentTimeSec + deltaSec);
  }

  seekTo(nextTimeSec: number): Promise<void> {
    return this._queue(async () => {
      const duration = this._meta.durationSec ?? Number.POSITIVE_INFINITY;
      const maxTime = Number.isFinite(duration) ? Math.max(0, duration - 0.25) : Number.MAX_SAFE_INTEGER;
      this._currentTimeSec = clamp(nextTimeSec, 0, maxTime);
      this._ended = false;
      if (this._playing) {
        await this._startDecoder(this._currentTimeSec);
      } else {
        this._statusMessage = `Seeked to ${formatClock(this._currentTimeSec)}`;
      }
    });
  }

  restart(): Promise<void> {
    return this.seekTo(0);
  }

  toggleMute(): Promise<void> {
    return this._queue(async () => {
      if (!this._audioAvailable) {
        this._audioStatus = "Audio unavailable on this platform";
        return;
      }
      this._audioMuted = !this._audioMuted;
      this._audioProcess?.setMuted(this._audioMuted);
      this._audioStatus = this._describeAudioState();
    });
  }

  changeVolumeBy(delta: number): Promise<void> {
    return this.setVolume(this._audioVolume + delta);
  }

  setVolume(nextVolume: number): Promise<void> {
    return this._queue(async () => {
      if (!this._audioAvailable) {
        this._audioStatus = "Audio unavailable on this platform";
        return;
      }
      this._audioVolume = clamp(Math.round(nextVolume), 0, 100);
      this._audioProcess?.setVolume(this._audioVolume);
      this._audioStatus = this._describeAudioState();
    });
  }

  toggleAudioEnabled(): Promise<void> {
    return this._queue(async () => {
      if (!this._audioAvailable) {
        this._audioStatus = "Audio unavailable on this platform";
        return;
      }

      this._audioEnabled = !this._audioEnabled;
      if (!this._audioEnabled) {
        this._stopAudioProcess();
      } else if (this._playing && this._currentAudioUrl) {
        this._startAudioProcess(this._currentAudioUrl, this._currentTimeSec);
      }
      this._audioStatus = this._describeAudioState();
    });
  }

  toggleSubtitles(): Promise<void> {
    return this._queue(async () => {
      await this._setSubtitlesEnabledInternal(!this._subtitlesEnabled);
    });
  }

  dispose(): void {
    this._disposed = true;
    this._stopDecoder("Stopped");
  }

  private _queue(task: () => Promise<void>): Promise<void> {
    this._serial = this._serial.then(task, task);
    return this._serial;
  }

  private _describeAudioState(): string {
    if (!this._audioAvailable) return "Audio unavailable on this platform";
    if (!this._audioEnabled) return "Audio off";
    if (this._audioMuted || this._audioVolume === 0) return `Muted (${this._audioVolume}%)`;
    return `Volume ${this._audioVolume}%`;
  }

  private async _resolvePlaybackSources(): Promise<YouTubePlaybackSources> {
    const ytDlp = await createYtDlp();
    const stdout = await ytDlp.execPromise([
      this._meta.url,
      "-f",
      "bestvideo[ext=mp4][vcodec!=none]+bestaudio[ext=m4a]/bestvideo[ext=mp4][vcodec!=none]+bestaudio[acodec*=aac]/bestvideo+bestaudio/best",
      "-g",
      "--no-warnings",
    ]);

    const lines = trimYtDlpStdout(stdout)
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);

    const videoUrl = lines[0];
    if (!videoUrl) {
      throw new Error("yt-dlp did not return a playable stream URL.");
    }

    return {
      videoUrl,
      audioUrl: lines[1] ?? lines[0],
    };
  }

  private _startAudioProcess(audioUrl: string, startTimeSec: number): void {
    if (!this._audioAvailable || !this._audioEnabled) {
      this._audioStatus = this._describeAudioState();
      return;
    }

    this._stopAudioProcess();
    this._audioStatus = "Audio starting…";

    const audio = new WindowsAudioProcess(
      audioUrl,
      startTimeSec,
      this._audioVolume,
      this._audioMuted,
      {
        onReady: () => {
          if (this._audioProcess !== audio) return;
          this._audioStatus = this._describeAudioState();
        },
        onError: (message) => {
          if (this._audioProcess !== audio) return;
          this._audioProcess = null;
          this._audioStatus = `Audio error: ${message}`;
          audio.dispose();
        },
        onExit: () => {
          if (this._audioProcess !== audio) return;
          this._audioProcess = null;
          if (this._audioEnabled && this._playing && !this._disposed) {
            this._audioStatus = "Audio stopped";
          }
        },
      },
    );

    this._audioProcess = audio;
  }

  private _stopAudioProcess(): void {
    const audio = this._audioProcess;
    this._audioProcess = null;
    audio?.dispose();
  }

  private async _setSubtitlesEnabledInternal(enabled: boolean): Promise<void> {
    if (!enabled) {
      this._subtitlesEnabled = false;
      this._subtitleStatus = this._subtitleTracks.length > 0 ? "Subtitles off" : "No subtitles found";
      return;
    }

    if (this._subtitleTracks.length === 0) {
      this._subtitlesEnabled = false;
      this._subtitleStatus = "No subtitles found";
      return;
    }

    if (this._subtitleCues.length === 0) {
      const track = chooseSubtitleTrack(this._subtitleTracks);
      if (!track) {
        this._subtitlesEnabled = false;
        this._subtitleStatus = "No usable subtitle track";
        return;
      }

      try {
        this._subtitleStatus = `Loading subtitles (${track.lang}${track.autoGenerated ? ", auto" : ""})…`;
        const cues = await loadSubtitleCues(track);
        if (cues.length === 0) {
          this._subtitlesEnabled = false;
          this._subtitleStatus = "Subtitle track was empty";
          return;
        }
        this._subtitleCues = cues;
        this._activeSubtitleTrack = track;
      } catch (error: any) {
        this._subtitlesEnabled = false;
        this._subtitleStatus = `Subtitle error: ${error?.message ?? String(error)}`;
        return;
      }
    }

    this._subtitlesEnabled = true;
    const track = this._activeSubtitleTrack;
    this._subtitleStatus = track
      ? `Subtitles on (${track.lang}${track.autoGenerated ? ", auto" : ""})`
      : "Subtitles on";
  }

  private _getSubtitleTextAt(currentTimeSec: number): string | undefined {
    if (!this._subtitleCues.length) return undefined;
    const cue = this._subtitleCues.find((item) => currentTimeSec >= item.startSec && currentTimeSec <= item.endSec);
    return cue?.text;
  }

  private async _startDecoder(startTimeSec: number): Promise<void> {
    this._stopDecoder();

    this._statusMessage = `Buffering ${this._meta.title}…`;
    this._ready = false;
    this._ended = false;
    this._stderrTail = "";
    this._carry = Buffer.alloc(0);

    const ffmpegPath = await getFfmpegPath();
    const sources = await this._resolvePlaybackSources();
    const playbackUrl = sources.videoUrl;
    this._currentAudioUrl = sources.audioUrl ?? null;
    const token = ++this._spawnToken;

    const filter = [
      `fps=${this.fps}`,
      `scale=${this.frameWidth}:${this.frameHeight}:force_original_aspect_ratio=decrease`,
      `pad=${this.frameWidth}:${this.frameHeight}:(ow-iw)/2:(oh-ih)/2:black`,
    ].join(",");

    const args = [
      "-hide_banner",
      "-loglevel",
      "error",
      "-reconnect",
      "1",
      "-reconnect_streamed",
      "1",
      "-reconnect_delay_max",
      "2",
      ...(startTimeSec > 0.05 ? ["-ss", startTimeSec.toFixed(3)] : []),
      "-i",
      playbackUrl,
      "-an",
      "-vf",
      filter,
      "-pix_fmt",
      "rgba",
      "-f",
      "rawvideo",
      "pipe:1",
    ];

    const child = spawn(ffmpegPath, args, {
      stdio: ["ignore", "pipe", "pipe"],
      windowsHide: true,
    });

    this._ffmpeg = child;
    this._playing = true;
    this._statusMessage = `Playing ${this._meta.title}`;
    if (this._audioEnabled && this._currentAudioUrl) {
      this._startAudioProcess(this._currentAudioUrl, startTimeSec);
    } else {
      this._audioStatus = this._describeAudioState();
    }

    child.stdout.on("data", (chunk: Buffer) => {
      if (this._disposed || token !== this._spawnToken) return;
      this._carry = Buffer.concat([this._carry, chunk]);
      while (this._carry.length >= FRAME_BYTES) {
        const frame = this._carry.subarray(0, FRAME_BYTES);
        this._frame.set(frame);
        this._carry = this._carry.subarray(FRAME_BYTES);
        this._currentTimeSec += 1 / this.fps;
        this._ready = true;
      }
    });

    child.stderr.on("data", (chunk: Buffer) => {
      this._stderrTail = `${this._stderrTail}${chunk.toString("utf8")}`.slice(-500);
    });

    child.on("error", (error) => {
      if (token !== this._spawnToken) return;
      this._playing = false;
      this._ready = false;
      this._statusMessage = `Playback error: ${error.message}`;
      this._stopAudioProcess();
    });

    child.on("close", () => {
      if (token !== this._spawnToken) return;
      this._ffmpeg = null;
      const wasPlaying = this._playing;
      this._playing = false;
      if (this._disposed) return;
      if (wasPlaying && !this._ended) {
        const nearEnd = this._meta.durationSec && this._currentTimeSec >= this._meta.durationSec - 1;
        if (nearEnd) {
          this._ended = true;
          this._statusMessage = "Finished";
        } else if (this._stderrTail.trim()) {
          this._statusMessage = `ffmpeg: ${this._stderrTail.trim()}`;
        } else {
          this._statusMessage = "Playback stopped";
        }
      }
    });
  }

  private _stopDecoder(nextStatus?: string): void {
    this._spawnToken++;
    this._stopAudioProcess();
    if (this._ffmpeg) {
      const child = this._ffmpeg;
      this._ffmpeg = null;
      try {
        child.kill("SIGTERM");
      } catch {
        // Ignore shutdown errors.
      }
    }
    this._playing = false;
    if (nextStatus) this._statusMessage = nextStatus;
    if (!this._disposed) {
      this._audioStatus = this._describeAudioState();
    }
  }
}
